language: go

go:
  - 1.7

before_install:
  - go get -u honnef.co/go/staticcheck/cmd/staticcheck
  - go get -u honnef.co/go/simple/cmd/gosimple
  - go get -u github.com/golang/lint/golint
  - go get -v github.com/Masterminds/glide
  - glide install

script:
  - pkgs=$(go list ./...|grep -v vendor)
  - test -z $(gofmt -s -l .)
  - go test -v -race $pkgs
  - go vet $pkgs
  - staticcheck $pkgs
  - gosimple $pkgs
  - golint $pkgs
